build:
    g++ sourceCrossroad.cpp sourceDodgeObject.cpp sourceDriveRobot.cpp sourceFreeRideLoop.cpp sourceGridFollowLoop.cpp sourceLineFollowLoop.cpp sourceMainFunctions.cpp sourcePIDController.cpp sourceSensors.cpp sourceSound.cpp BrickPi3.cpp main.cpp -o run

